name: On-Demand Selenium Tests

on:
  workflow_dispatch: # Enables manual triggering of the workflow
    inputs:
      browser:
        description: 'Browser to run the tests (chrome, firefox, etc.)'
        required: false
        default: 'chrome'

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [${{ github.event.inputs.browser }}] # Use the selected browser input

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust Java version if necessary

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Selenium Tests
        run: mvn test -DsuiteXmlFile=src/test/testng-${{ matrix.browser }}.xml
